services:
  - type: web
    name: nexus-core
    env: node

    buildCommand: |
      echo "NEXUS BUILD TEST"
      npm install
      apt-get update && apt-get install -y deno
      deno --version
      python3 -m pip install -U yt-dlp
      yt-dlp --version

    startCommand: npm start

    envVars:
      - key: PORT
        value: 10000
